# Generated by Django 4.2.21 on 2025-06-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('transaction_date', models.DateField()),
                ('total_amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=100)),
                ('shipping_method', models.CharField(max_length=100)),
                ('delivery_time', models.CharField(max_length=50)),
                ('coupon_code', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('product_id', models.IntegerField()),
                ('sales_factor', models.FloatField()),
            ],
        ),
    ]
